name: 'Deploy to GitHub Pages'
on:
  push:	
    branches:
      - main
    paths:	
      - 'public/**'
      
jobs:
  deploy:
    name: Push public to master
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@main

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: master
        FOLDER: public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}